[package]
authors = ["eric@harris-braun.com"]
edition = "2018"
name = "where_ludotheque"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "where_ludotheque"

[dependencies]
serde = "1.0"
hdk = "0.0.142"
holo_hash = {version = "0.0.30", features = ["encoding"]}

zome_utils = { git = "https://github.com/ddd-mtl/zome-utils", branch = "142" }

ludotheque_integrity = { package = "where_ludotheque_integrity", path = "../ludotheque_integrity" }
