[package]
name = "where_integrity_zome"
authors = ["eric@harris-braun.com"]
version.workspace = true
rust-version.workspace = true
edition.workspace = true


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
serde.workspace = true
hdi.workspace = true
