[package]
authors = ["eric@harris-braun.com"]
edition = "2018"
name = "where_ludotheque_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "where_ludotheque_integrity"

[dependencies]
serde = "1.0"
hdi = { version = "0.1.3", default-features = false }
