/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "where" */
export const whereFunctionNames: FunctionName[] = [
	"entry_defs",
	"add_here",
	"update_here",
	"delete_here",
	"get_heres",
	"hide_space",
	"unhide_space",
	"get_hidden_spaces",

	"get_session",
	"get_session_from_eh",
	"get_space_sessions",
	"create_sessions",
	"create_next_session",

	"notify_peers",];


/** Generate tuple array of function names with given zomeName */
export function generateWhereZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   let fns: [ZomeName, FunctionName][] = [];
   for (const fn of whereFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zWhere" */
export const whereZomeFunctions: [ZomeName, FunctionName][] = generateWhereZomeFunctionsArray("zWhere");
