[package]
authors = ["eric@harris-braun.com"]
edition = "2018"
name = "where"
version = "0.0.1-alpha1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "where"

[dependencies]
chrono = {version = "=0.4.19", features = ['alloc', 'std']}
derive_more = "0.99"
serde = "1.0"
thiserror = "1.0.20"
tracing = { version = "0.1", default-features = false }

hdk = "0.0.142"
holo_hash = {version = "0.0.30", features = ["encoding"]}

zome_utils = { git = "https://github.com/ddd-mtl/zome-utils", branch = "142" }

playset_integrity = { package = "where_playset_integrity", path = "../playset_integrity" }
where_integrity = { path = "../where_integrity" }


[dev-dependencies]
futures = "0.3.1"
nanoid = "0.3"
observability = "0.1.2"
stream-cancel = "0.8.0"
tokio = {version = "1.3", features = ["full"]}
