[package]
authors = ["eric@harris-braun.com"]
edition = "2018"
name = "where_playset"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "where_playset"

[dependencies]
serde = "1.0"
hc_utils = {git = "https://github.com/holochain/hc-utils", rev = "1da00e5677d50a837ebcf733e9b2d69064f814f0", package = "hc_utils"}
hdk = "0.0.123"
holo_hash = {version = "0.0.20", features = ["encoding"]}
zome_utils = { git = "https://github.com/ddd-mtl/zome-utils", branch = "123" }
