name: build-electron

on:
  workflow_call:

env:
  USE_HARD_LINKS: false

jobs:
  # Build the dna & happ
  call-build-webhapps:
    uses: ./.github/workflows/build-webhapps.yml

  # upload the app package for each target os
  build-binaries:
    needs: call-build-webhapps
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
      # Set NPM shell (windows-only)
      - name: Set NPM shell (windows-only)
        if: ${{ runner.os == 'Windows' }}
        shell: bash
        run: |
          npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@master
        with:
          name: all-happ-artifact
          path: artifacts
      # Display artifacts folder
      - name: Display artifacts folder
        run: ls
        working-directory: artifacts
      # Dispatch artifacts
      - name: Dispatch artifacts
        run: |
          cp artifacts/where.happ ./electron/bin
          cp artifacts/where_zome_hash.txt ./electron/bin
          cp artifacts/ludotheque_zome_hash.txt ./electron/bin
      # Install npm dependencies
      - name: Install npm dependencies
        run: |
          npm install
      # Build webapp
      - name: Build webapp
        run: |
          npm run build:webapp
      # Build electron app
      - name: Build electron app
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build -w electron
      # Dist Electron
      - name: Dist Electron
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist:electron
      # List out-builder folder
      - name: list out-builder folder
        continue-on-error: true
        run: ls -R
        working-directory: electron/out-builder
      # list bin folder
      - name: list bin folder
        continue-on-error: true
        run: ls
        working-directory: electron/bin
      # Move binary for each platform
      - name: Move binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp electron/out-builder/Where* ./artifacts
      # List uploaded files
      - name: List artifacts folder
        run: ls -R
        working-directory: artifacts
      # "upload" artifacts
      - uses: actions/upload-artifact@master
        with:
          name: all-happ-artifact
          path: artifacts
