name: Release x64

on:
  push:
     tags:
      - v[0-9]+.*

env:
  WHERE_VERSION: 0.1.0
  USE_HARD_LINKS: false

jobs:
  # the create-release would be used once we want to create a specific release based on if the commit has a tag
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build the dna & happ
  call-build-webhapps:
    uses: ./.github/workflows/build-webhapps.yml

  # upload the app package for each target os
  build-binaries:
    needs: call-build-webhapps
    strategy:
      #fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@master
        with:
          name: all-happ-artifact
      # Dispatch artifacts
      - name: Dispatch artifacts
        run: |
          cp ./where.happ ./electron/bin
          cp ./where_zome_hash.txt ./electron/bin
          cp ./ludotheque_zome_hash.txt ./electron/bin
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install
          npm install electron-builder
      # Build web-ui
      - name: Build web-ui
        run: |
          npm run build:webui
      # Build electron app
      - name: Build electron app
        shell: bash
        env:
          #WIN_CSC_LINK: ${{ steps.write_file.outputs.filePath }}
          #WIN_CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
          APPLE_DEV_IDENTITY: ${{ secrets.APPLE_DEV_IDENTITY }}
          APPLE_ID_EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          DEBUG: electron-osx-sign*,electron-notarize*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build -w electron
      # Dist Electron
      - name: Dist Electron
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist:build -w electron
      # List out-builder folder
      - name: list out-builder folder
        continue-on-error: true
        run: ls -R
        working-directory: electron/out-builder
      # list bin folder
      - name: list bin folder
        continue-on-error: true
        run: ls
        working-directory: electron/bin
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "electron/out-builder/Where-$WHERE_VERSION.AppImage" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where-web-ui.zip" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where-we_applet-ui.zip" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where.webhapp" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where-we_applet.webhapp" --clobber          
          gh release upload "${GITHUB_REF#refs/tags/}" "where.happ" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where.dna" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "ludotheque.dna" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where_zome.wasm" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where_integrity_zome.wasm" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where_ludotheque_zome.wasm" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where_ludotheque_integrity_zome.wasm" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where_ludotheque_zome.wasm" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}" "where_playset_integrity_zome.wasm" --clobber          
          gh release upload "${GITHUB_REF#refs/tags/}" "where_playset_zome.wasm" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}"  "electron/out/Where-$WHERE_VERSION.dmg" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$($env:GITHUB_REF -replace "refs/tags/")" "electron/out/Where.Setup.$env:WHERE_VERSION.exe" --clobber
