name: Release x64

on:
  push:
     tags:
      - v[0-9]+.*

env:
  WHERE_VERSION: 0.0.9
  USE_HARD_LINKS: false

jobs:
  # the create-release would be used once we want to create a specific release based on if the commit has a tag
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build the dna & happ
  call-build-dna:
    uses: ./.github/workflows/build-dna.yml

  # upload the app package for each target os
  build-binaries:
    needs: call-build-dna
    strategy:
      #fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # rm the dna files from repository
      - name: clearing precompiled dna files
        continue-on-error: true
        run: |
          rm dna/workdir/dna-where/where.dna
          rm dna/workdir/happ-where/where.happ
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@master
        with:
          name: where-happ-artifact
          path: dna/workdir/happ-where
      - uses: actions/download-artifact@master
        with:
          name: where-webapp-artifact
          path: workdir
      - uses: actions/download-artifact@master
        with:
          name: where-hash-artifact
          path: dna
      # Check if exist
      - name: list webhapp
        continue-on-error: true
        run: ls -R
        working-directory: workdir
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install
      # Build happ
      - name: Build happ
        run: |
          npm run build
      # Setup sign & notarize
      #- name: Setup sign and notarize (macos only)
      #  continue-on-error: true
      #  if: ${{ runner.os == 'macOs' }}
      #  uses:  figleafteam/import-codesign-certs@v2
      #  with:
      #    p12-file-base64: ${{ secrets.HBE_APPLE_CERTIFICATE_BASE64 }}
      #    p12-password: ${{ secrets.HBE_APPLE_CERTIFICATE_PASS }}
      # Build installers and binaries
      - name: Build binaries
        shell: bash
        env:
          #WIN_CSC_LINK: ${{ steps.write_file.outputs.filePath }}
          #WIN_CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
          APPLE_DEV_IDENTITY: ${{ secrets.APPLE_DEV_IDENTITY }}
          APPLE_ID_EMAIL: ${{ secrets.APPLE_ID_EMAIL }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          DEBUG: electron-osx-sign*,electron-notarize*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist
      # upload installers and binaries
      - name: list builds
        continue-on-error: true
        run: ls
        working-directory: electron/out
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}"  "electron/out/Where-$WHERE_VERSION.AppImage" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}"  "dna/workdir/happ-where/where.happ" --clobber
          gh release upload "${GITHUB_REF#refs/tags/}"  "workdir/where.webhapp" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}"  "electron/out/Where-$WHERE_VERSION.dmg" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$($env:GITHUB_REF -replace "refs/tags/")" "electron/out/Where.Setup.$env:WHERE_VERSION.exe" --clobber
