name: test-workflow x64

on: workflow_dispatch

env:
  WHERE_VERSION: 0.0.9
  USE_HARD_LINKS: false

jobs:
  # Build the dna & happ
  call-build-dna:
    uses: ./.github/workflows/build-dna.yml

  # upload the app package for each target os
  build-binaries:
    needs: call-build-dna
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # Check if exist
      #- name: tsc
      #   continue-on-error: true
      #  run: |
      #     tsc --version
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@master
        with:
          name: where-happ-artifact
          path: dna/workdir/happ-where
      - uses: actions/download-artifact@master
        with:
          name: where-webapp-artifact
          path: workdir
      - uses: actions/download-artifact@master
        with:
          name: where-hash-artifact
          path: electron/binaries
      # Setup npm
      - name: Install nodejs dependencies
        run: |
          npm install
      # Build happ
      - name: Build happ
        run: |
          npm run build
      # Build installers and binaries
      - name: Build binaries
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist
      # Build tar.gz
      - name: Build tar.gz
        if: ${{ runner.os == 'Linux' }}
        continue-on-error: true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist-linux
          gh release upload "manual-release" "electron/out/where-$WHERE_VERSION.tar.gz" --clobber
      # upload installers and binaries
      - name: list builds
        continue-on-error: true
        run: ls -R
        working-directory: electron/out
#      #
#      - name: list releases
#        continue-on-error: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          gh release list
      # upload binary for each platform
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out/Where-$WHERE_VERSION.AppImage" --clobber
          gh release upload "manual-release"  "dna/workdir/happ-where/where.happ" --clobber
          gh release upload "manual-release"  "workdir/where.webhapp" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out/Where-$WHERE_VERSION.dmg" --clobber
      - name: upload binary (Windows only)
        if: ${{ runner.os == 'Windows' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "manual-release" "electron/out/Where.Setup.$env:WHERE_VERSION.exe" --clobber
