name: test-workflow x64

on: workflow_dispatch

jobs:
  call-build-electron:
    uses: ./.github/workflows/build-electron.yml

  # upload the artifacts
  upload-assets:
    needs: call-build-electron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Download previously uploaded artifacts
      - uses: actions/download-artifact@v3
        with:
          name: all-happ-artifact
          path: artifacts
      # Display artifacts folder
      - name: Display artifacts folder
        run: ls
        working-directory: artifacts
      # upload all artifacts
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: artifacts
        run: |
          rm -f *.blockmap
          echo ludotheque
          gh release upload "manual-release" ludotheque* --clobber          
          echo place*
          gh release upload "manual-release" place* --clobber
          echo Place*
          gh release upload "manual-release" Place* --clobber
